# Generated by Django 5.0.7 on 2024-07-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('socioeconomic_status', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers', to='accounts.surveyorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('place_of_delivery', models.CharField(max_length=100)),
                ('type_of_delivery', models.CharField(max_length=100)),
                ('birth_attendant', models.CharField(max_length=100)),
                ('complications', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_delivery', to='accounts.surveyorprofile')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_delivery', to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='AntenatalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('hemoglobin_level', models.FloatField()),
                ('screening_results', models.TextField()),
                ('immunizations', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenatal_care', to='accounts.surveyorprofile')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_care', to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='ObstetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_pregnancies', models.PositiveIntegerField()),
                ('live_births', models.PositiveIntegerField()),
                ('stillbirths', models.PositiveIntegerField()),
                ('miscarriages', models.PositiveIntegerField()),
                ('complications', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_history', to='mothers.mother')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obstetric_history', to='accounts.surveyorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostnatalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('health_assessment', models.TextField()),
                ('breastfeeding_support', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_care', to='mothers.mother')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_care', to='accounts.surveyorprofile')),
            ],
        ),
    ]
