# Generated by Django 5.0.7 on 2024-07-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '__first__'),
        ('surveyors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('birth_weight', models.FloatField()),
                ('birth_length', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mothers.mother')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='surveyors.surveyor')),
            ],
        ),
        migrations.CreateModel(
            name='InfantChildHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('developmental_milestones', models.TextField()),
                ('immunizations', models.TextField()),
                ('nutrition', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infant_child_health', to='children.child')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infant_child_health', to='surveyors.surveyor')),
            ],
        ),
        migrations.CreateModel(
            name='NeonatalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apgar_score', models.CharField(max_length=10)),
                ('newborn_screening_results', models.TextField()),
                ('congenital_conditions', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neonatal_health', to='children.child')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neonatal_health', to='surveyors.surveyor')),
            ],
        ),
    ]
